class SuraModels {
  final int index;
  final String nameAr;
  final String nameEn;
  final String verses;

  SuraModels({
    required this.index,
    required this.nameAr,
    required this.nameEn,
    required this.verses,
  });
}

List<SuraModels> suras = [
  SuraModels(
    index: 0,
    nameAr: 'الفاتحة',
    nameEn: 'Al-Fatihah',
    verses: '7 verses',
  ),
  SuraModels(
    index: 1,
    nameAr: 'البقرة',
    nameEn: 'Al-Baqarah',
    verses: '286 verses',
  ),
  SuraModels(
    index: 2,
    nameAr: 'آل عمران',
    nameEn: 'Al-Imran',
    verses: '200 verses',
  ),
  SuraModels(
    index: 3,
    nameAr: 'النساء',
    nameEn: 'An-Nisa',
    verses: '176 verses',
  ),
  SuraModels(
    index: 4,
    nameAr: 'المائدة',
    nameEn: 'Al-Maidah',
    verses: '120 verses',
  ),
  SuraModels(
    index: 5,
    nameAr: 'الأنعام',
    nameEn: 'Al-Anam',
    verses: '165 verses',
  ),
  SuraModels(
    index: 6,
    nameAr: 'الأعراف',
    nameEn: 'Al-Araf',
    verses: '206 verses',
  ),
  SuraModels(
    index: 7,
    nameAr: 'الأنفال',
    nameEn: 'Al-Anfal',
    verses: '75 verses',
  ),
  SuraModels(
    index: 8,
    nameAr: 'التوبة',
    nameEn: 'At-Tawba',
    verses: '129 verses',
  ),
  SuraModels(
    index: 9,
    nameAr: 'يونس',
    nameEn: 'Yunus',
    verses: '109 verses',
  ),
    SuraModels(
    index: 10,
    nameAr: 'هود',
    nameEn: 'Hud',
    verses: '123 verses',
  ),
  SuraModels(
    index: 11,
    nameAr: 'يوسف',
    nameEn: 'Yusuf',
    verses: '111 verses',
  ),
  SuraModels(
    index: 12,
    nameAr: 'الرعد',
    nameEn: 'Ar-Ra’d',
    verses: '43 verses',
  ),
  SuraModels(
    index: 13,
    nameAr: 'ابراهيم',
    nameEn: 'Ibrahim',
    verses: '52 verses',
  ),
  SuraModels(
    index: 14,
    nameAr: 'الحجر',
    nameEn: 'Al-Hijr',
    verses: '99 verses',
  ),
  SuraModels(
    index: 15,
    nameAr: 'النحل',
    nameEn: 'An-Nahl',
    verses: '128 verses',
  ),
  SuraModels(
    index: 16,
    nameAr: 'الإسراء',
    nameEn: 'Al-Isra',
    verses: '111 verses',
  ),
  SuraModels(
    index: 17,
    nameAr: 'الكهف',
    nameEn: 'Al-Kahf',
    verses: '110 verses',
  ),
  SuraModels(
    index: 18,
    nameAr: 'مريم',
    nameEn: 'Maryam',
    verses: '98 verses',
  ),
  SuraModels(
    index: 19,
    nameAr: 'طه',
    nameEn: 'Taha',
    verses: '135 verses',
  ),
  SuraModels(
    index: 20,
    nameAr: 'الأنبياء',
    nameEn: 'Al-Anbiyaa',
    verses: '112 verses',
  ),
  SuraModels(
    index: 21,
    nameAr: 'الحج',
    nameEn: 'Al-Hajj',
    verses: '78 verses',
  ),
  SuraModels(
    index: 22,
    nameAr: 'المؤمنون',
    nameEn: 'Al-Mu’men',
    verses: '118 verses',
  ),
  SuraModels(
    index: 23,
    nameAr: 'النور',
    nameEn: 'An-Nur',
    verses: '64 verses',
  ),
  SuraModels(
    index: 24,
    nameAr: 'الفرقان',
    nameEn: 'Al-Furqaan',
    verses: '77 verses',
  ),
  SuraModels(
    index: 25,
    nameAr: 'الشعراء',
    nameEn: 'Ash-Shu’ara',
    verses: '227 verses',
  ),
  SuraModels(
    index: 26,
    nameAr: 'النمل',
    nameEn: 'An-Naml',
    verses: '93 verses',
  ),
  SuraModels(
    index: 27,
    nameAr: 'القصص',
    nameEn: 'Al-Qasas',
    verses: '88 verses',
  ),
  SuraModels(
    index: 28,
    nameAr: 'العنكبوت',
    nameEn: 'Al-’Ankabut',
    verses: '69 verses',
  ),
  SuraModels(
    index: 29,
    nameAr: 'الروم',
    nameEn: 'Ar-Room',
    verses: '60 verses',
  ),
  SuraModels(
    index: 30,
    nameAr: 'لقمان',
    nameEn: 'Luqman',
    verses: '34 verses',
  ),
  SuraModels(
    index: 31,
    nameAr: 'السجدة',
    nameEn: 'As-Sajdah',
    verses: '30 verses',
  ),
  SuraModels(
    index: 32,
    nameAr: 'الأحزاب',
    nameEn: 'Al-Ahzab',
    verses: '73 verses',
  ),
  SuraModels(
    index: 33,
    nameAr: 'سبأ',
    nameEn: 'Saba',
    verses: '54 verses',
  ),
  SuraModels(
    index: 34,
    nameAr: 'فاطر',
    nameEn: 'Fatir',
    verses: '45 verses',
  ),
  SuraModels(
    index: 35,
    nameAr: 'يس',
    nameEn: 'Yaseen',
    verses: '83 verses',
  ),
  SuraModels(
    index: 36,
    nameAr: 'الصافات',
    nameEn: 'As-Saaffat',
    verses: '182 verses',
  ),
  SuraModels(
    index: 37,
    nameAr: 'ص',
    nameEn: 'Saad',
    verses: '88 verses',
  ),
  SuraModels(
    index: 38,
    nameAr: 'الزمر',
    nameEn: 'Az-Zumar',
    verses: '75 verses',
  ),
  SuraModels(
    index: 39,
    nameAr: 'غافر',
    nameEn: 'Ghafir',
    verses: '85 verses',
  ),
  SuraModels(
    index: 40,
    nameAr: 'فصلت',
    nameEn: 'Fussilat',
    verses: '54 verses',
  ),
  SuraModels(
    index: 41,
    nameAr: 'الشورى',
    nameEn: 'Ash-Shura',
    verses: '53 verses',
  ),
  SuraModels(
    index: 42,
    nameAr: 'الزخرف',
    nameEn: 'Az-Zukhruf',
    verses: '89 verses',
  ),
  SuraModels(
    index: 43,
    nameAr: 'الدخان',
    nameEn: 'Ad-Dukhan',
    verses: '59 verses',
  ),
  SuraModels(
    index: 44,
    nameAr: 'الجاثية',
    nameEn: 'Al-Jathiyah',
    verses: '37 verses',
  ),
  SuraModels(
    index: 45,
    nameAr: 'الاحقاف',
    nameEn: 'Al-Ahqaf',
    verses: '35 verses',
  ),
  SuraModels(
    index: 46,
    nameAr: 'محمد',
    nameEn: 'Muhammad',
    verses: '38 verses',
  ),
  SuraModels(
    index: 47,
    nameAr: 'الفتح',
    nameEn: 'Al-Fath',
    verses: '29 verses',
  ),
  SuraModels(
    index: 48,
    nameAr: 'الحجرات',
    nameEn: 'Al-Hujurat',
    verses: '18 verses',
  ),
  SuraModels(
    index: 49,
    nameAr: 'ق',
    nameEn: 'Qaf',
    verses: '45 verses',
  ),
  SuraModels(
    index: 50,
    nameAr: 'الذاريات',
    nameEn: 'Adh-Dhariyat',
    verses: '60 verses',
  ),
  SuraModels(
    index: 51,
    nameAr: 'الطور',
    nameEn: 'At-Tur',
    verses: '49 verses',
  ),
  SuraModels(
    index: 52,
    nameAr: 'النجم',
    nameEn: 'An-Najm',
    verses: '62 verses',
  ),
  SuraModels(
    index: 53,
    nameAr: 'القمر',
    nameEn: 'Al-Qamar',
    verses: '55 verses',
  ),
  SuraModels(
    index: 54,
    nameAr: 'الرحمن',
    nameEn: 'Ar-Rahman',
    verses: '78 verses',
  ),
  SuraModels(
    index: 55,
    nameAr: 'الواقعة',
    nameEn: 'Al-Waqia',
    verses: '96 verses',
  ),
  SuraModels(
    index: 56,
    nameAr: 'الحديد',
    nameEn: 'Al-Hadid',
    verses: '29 verses',
  ),
  SuraModels(
    index: 57,
    nameAr: 'المجادلة',
    nameEn: 'Al-Mujadila',
    verses: '22 verses',
  ),
  SuraModels(
    index: 58,
    nameAr: 'الحشر',
    nameEn: 'Al-Hashr',
    verses: '24 verses',
  ),
  SuraModels(
    index: 59,
    nameAr: 'الممتحنة',
    nameEn: 'Al-Mumtahanah',
    verses: '13 verses',
  ),
  SuraModels(
    index: 60,
    nameAr: 'الصف',
    nameEn: 'As-Saff',
    verses: '14 verses',
  ),
  SuraModels(
    index: 61,
    nameAr: 'الجمعة',
    nameEn: 'Al-Jumuah',
    verses: '11 verses',
  ),
  SuraModels(
    index: 62,
    nameAr: 'المنافقون',
    nameEn: 'Al-Munafiqun',
    verses: '11 verses',
  ),
  SuraModels(
    index: 63,
    nameAr: 'التغابن',
    nameEn: 'At-Taghabun',
    verses: '18 verses',
  ),
  SuraModels(
    index: 64,
    nameAr: 'الطلاق',
    nameEn: 'At-Talaq',
    verses: '12 verses',
  ),
  SuraModels(
    index: 65,
    nameAr: 'التحريم',
    nameEn: 'At-Tahrim',
    verses: '12 verses',
  ),
  SuraModels(
    index: 66,
    nameAr: 'الملك',
    nameEn: 'Al-Mulk',
    verses: '30 verses',
  ),
  SuraModels(
    index: 67,
    nameAr: 'القلم',
    nameEn: 'Al-Qalam',
    verses: '52 verses',
  ),
  SuraModels(
    index: 68,
    nameAr: 'الحاقة',
    nameEn: 'Al-Haqqah',
    verses: '52 verses',
  ),
  SuraModels(
    index: 69,
    nameAr: 'المعارج',
    nameEn: 'Al-Ma’arij',
    verses: '44 verses',
  ),
  SuraModels(
    index: 70,
    nameAr: 'نوح',
    nameEn: 'Nuh',
    verses: '28 verses',
  ),
  SuraModels(
    index: 71,
    nameAr: 'الجن',
    nameEn: 'Al-Jinn',
    verses: '28 verses',
  ),
  SuraModels(
    index: 72,
    nameAr: 'المزمل',
    nameEn: 'Al-Muzzammil',
    verses: '20 verses',
  ),
  SuraModels(
    index: 73,
    nameAr: 'المدثر',
    nameEn: 'Al-Muddathir',
    verses: '56 verses',
  ),
  SuraModels(
    index: 74,
    nameAr: 'القيامة',
    nameEn: 'Al-Qiyamah',
    verses: '40 verses',
  ),
  SuraModels(
    index: 75,
    nameAr: 'الانسان',
    nameEn: 'Al-Insan',
    verses: '31 verses',
  ),
  SuraModels(
    index: 76,
    nameAr: 'المرسلات',
    nameEn: 'Al-Mursalat',
    verses: '50 verses',
  ),
  SuraModels(
    index: 77,
    nameAr: 'النبأ',
    nameEn: 'An-Naba',
    verses: '40 verses',
  ),
  SuraModels(
    index: 78,
    nameAr: 'النازعات',
    nameEn: 'An-Nazi’at',
    verses: '46 verses',
  ),
  SuraModels(
    index: 79,
    nameAr: 'عبس',
    nameEn: 'Abasa',
    verses: '42 verses',
  ),
  SuraModels(
    index: 80,
    nameAr: 'التكوير',
    nameEn: 'At-Takwir',
    verses: '29 verses',
  ),
  SuraModels(
    index: 81,
    nameAr: 'الانفطار',
    nameEn: 'Al-Infitar',
    verses: '19 verses',
  ),
  SuraModels(
    index: 82,
    nameAr: 'المطففين',
    nameEn: 'Al-Mutaffifin',
    verses: '36 verses',
  ),
  SuraModels(
    index: 83,
    nameAr: 'الانشقاق',
    nameEn: 'Al-Inshiqaq',
    verses: '25 verses',
  ),
  SuraModels(
    index: 84,
    nameAr: 'البروج',
    nameEn: 'Al-Buruj',
    verses: '22 verses',
  ),
  SuraModels(
    index: 85,
    nameAr: 'الطارق',
    nameEn: 'At-Tariq',
    verses: '17 verses',
  ),
  SuraModels(
    index: 86,
    nameAr: 'الأعلى',
    nameEn: 'Al-A’la',
    verses: '19 verses',
  ),
  SuraModels(
    index: 87,
    nameAr: 'الغاشية',
    nameEn: 'Al-Ghashiyah',
    verses: '26 verses',
  ),
  SuraModels(
    index: 88,
    nameAr: 'الفجر',
    nameEn: 'Al-Fajr',
    verses: '30 verses',
  ),
  SuraModels(
    index: 89,
    nameAr: 'البلد',
    nameEn: 'Al-Balad',
    verses: '20 verses',
  ),
  SuraModels(
    index: 90,
    nameAr: 'الشمس',
    nameEn: 'Ash-Shams',
    verses: '15 verses',
  ),
  SuraModels(
    index: 91,
    nameAr: 'الليل',
    nameEn: 'Al-Layl',
    verses: '21 verses',
  ),
  SuraModels(
    index: 92,
    nameAr: 'الضحى',
    nameEn: 'Ad-Duhaa',
    verses: '11 verses',
  ),
  SuraModels(
    index: 93,
    nameAr: 'الشرح',
    nameEn: 'Ash-Sharh',
    verses: '8 verses',
  ),
  SuraModels(
    index: 94,
    nameAr: 'التين',
    nameEn: 'At-Tin',
    verses: '8 verses',
  ),
  SuraModels(
    index: 95,
    nameAr: 'العلق',
    nameEn: 'Al-Alaq',
    verses: '19 verses',
  ),
  SuraModels(
    index: 96,
    nameAr: 'القدر',
    nameEn: 'Al-Qadr',
    verses: '5 verses',
  ),
  SuraModels(
    index: 97,
    nameAr: 'البينة',
    nameEn: 'Al-Bayyinah',
    verses: '8 verses',
  ),
  SuraModels(
    index: 98,
    nameAr: 'الزلزلة',
    nameEn: 'Az-Zalzalah',
    verses: '8 verses',
  ),
  SuraModels(
    index: 99,
    nameAr: 'العاديات',
    nameEn: 'Al-Adiyat',
    verses: '11 verses',
  ),
  SuraModels(
    index: 100,
    nameAr: 'القارعة',
    nameEn: 'Al-Qari’ah',
    verses: '11 verses',
  ),
  SuraModels(
    index: 101,
    nameAr: 'التكاثر',
    nameEn: 'At-Takathur',
    verses: '8 verses',
  ),
  SuraModels(
    index: 102,
    nameAr: 'العصر',
    nameEn: 'Al-Asr',
    verses: '3 verses',
  ),
  SuraModels(
    index: 103,
    nameAr: 'الهمزة',
    nameEn: 'Al-Humazah',
    verses: '9 verses',
  ),
  SuraModels(
    index: 104,
    nameAr: 'الفيل',
    nameEn: 'Al-Fil',
    verses: '5 verses',
  ),
  SuraModels(
    index: 105,
    nameAr: 'قريش',
    nameEn: 'Quraysh',
    verses: '4 verses',
  ),
  SuraModels(
    index: 106,
    nameAr: 'الماعون',
    nameEn: 'Al-Ma’un',
    verses: '7 verses',
  ),
  SuraModels(
    index: 107,
    nameAr: 'الكوثر',
    nameEn: 'Al-Kawthar',
    verses: '3 verses',
  ),
  SuraModels(
    index: 108,
    nameAr: 'الكافرون',
    nameEn: 'Al-Kafirun',
    verses: '6 verses',
  ),
  SuraModels(
    index: 109,
    nameAr: 'النصر',
    nameEn: 'An-Nasr',
    verses: '3 verses',
  ),
  SuraModels(
    index: 110,
    nameAr: 'المسد',
    nameEn: 'Al-Masad',
    verses: '5 verses',
  ),
  SuraModels(
    index: 111,
    nameAr: 'الإخلاص',
    nameEn: 'Al-Ikhlas',
    verses: '4 verses',
  ),
  SuraModels(
    index: 112,
    nameAr: 'الفلق',
    nameEn: 'Al-Falaq',
    verses: '5 verses',
  ),
  SuraModels(
    index: 113,
    nameAr: 'الناس',
    nameEn: 'An-Nas',
    verses: '6 verses',
  ),
];
